title: slans' Unofficial DCS Documentation
description: An unofficial DCS new user guide, setup and troubleshooting manual.
theme: just-the-docs

url: https://slans04.github.io/Unofficial_DCS_Setup

#aux_links: # remove if you don't want this link to appear on your pages
#  Template Repository: https://github.com/slans04/Unofficial_DCS_Setup
